// Avoid `console` errors in browsers that lack a console.
(function() {
    var method;
    var noop = function noop() {};
    var methods = [
        'assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error',
        'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log',
        'markTimeline', 'profile', 'profileEnd', 'table', 'time', 'timeEnd',
        'timeStamp', 'trace', 'warn'
    ];
    var length = methods.length;
    var console = (window.console = window.console || {});

    while (length--) {
        method = methods[length];

        // Only stub undefined methods.
        if (!console[method]) {
            console[method] = noop;
        }
    }
}());


(function(b,D,M){function c(a,g,c){a=D.createElement(a);g&&(a.id=p+g);c&&(a.style.cssText=c);return b(a)}function N(a){var b=j.length,a=(n+a)%b;return 0>a?b+a:a}function h(a,b){return Math.round((/%/.test(a)?("x"===b?O():P())/100:1)*parseInt(a,10))}function ga(b){return a.photo||/\.(gif|png|jp(e|g|eg)|bmp|ico)((#|\?).*)?$/i.test(b)}function O(){return M.innerWidth||q.width()}function P(){return M.innerHeight||q.height()}function ha(){var x,g=b.data(m,t);null==g?(a=b.extend({},U),console&&console.log&&
console.log("Error: cboxElement missing settings object")):a=b.extend({},g);for(x in a)b.isFunction(a[x])&&"on"!==x.slice(0,2)&&(a[x]=a[x].call(m));a.rel=a.rel||m.rel||b(m).data("rel")||"nofollow";a.href=a.href||b(m).attr("href");a.title=a.title||m.title;"string"===typeof a.href&&(a.href=b.trim(a.href))}function B(a,g){b.event.trigger(a);g&&g.call(m)}function na(){var b,g=p+"Slideshow_",c="click."+p,e,r;a.slideshow&&j[1]?(e=function(){E.html(a.slideshowStop).unbind(c).bind(V,function(){if(a.loop||
j[n+1])b=setTimeout(f.next,a.slideshowSpeed)}).bind(W,function(){clearTimeout(b)}).one(c+" "+Q,r);i.removeClass(g+"off").addClass(g+"on");b=setTimeout(f.next,a.slideshowSpeed)},r=function(){clearTimeout(b);E.html(a.slideshowStart).unbind([V,W,Q,c].join(" ")).one(c,function(){f.next();e()});i.removeClass(g+"on").addClass(g+"off")},a.slideshowAuto?e():r()):i.removeClass(g+"off "+g+"on")}function ia(c){if(!R){m=c;ha();j=b(m);n=0;"nofollow"!==a.rel&&(j=b("."+F).filter(function(){var c=b.data(this,t),
x;c&&(x=b(this).data("rel")||c.rel||this.rel);return x===a.rel}),n=j.index(m),-1===n&&(j=j.add(m),n=j.length-1));if(!u){u=G=!0;i.show();if(a.returnFocus)b(m).blur().one(ja,function(){b(this).focus()});y.css({opacity:+a.opacity,cursor:a.overlayClose?"pointer":"auto"}).show();a.w=h(a.initialWidth,"x");a.h=h(a.initialHeight,"y");f.position();H&&q.bind("resize."+S+" scroll."+S,function(){y.css({width:O(),height:P(),top:q.scrollTop(),left:q.scrollLeft()})}).trigger("resize."+S);B(ka,a.onOpen);X.add(Y).hide();
Z.html(a.close).show()}f.load(!0)}}function la(){!i&&D.body&&($=!1,q=b(M),i=c(e).attr({id:t,"class":I?p+(H?"IE6":"IE"):""}).hide(),y=c(e,"Overlay",H?"position:absolute":"").hide(),aa=c(e,"LoadingOverlay").add(c(e,"LoadingGraphic")),C=c(e,"Wrapper"),s=c(e,"Content").append(l=c(e,"LoadedContent","width:0; height:0; overflow:hidden"),Y=c(e,"Title"),ba=c(e,"Current"),J=c(e,"Next"),K=c(e,"Previous"),E=c(e,"Slideshow").bind(ka,na),Z=c(e,"Close")),C.append(c(e).append(c(e,"TopLeft"),ca=c(e,"TopCenter"),
c(e,"TopRight")),c(e,!1,"clear:left").append(da=c(e,"MiddleLeft"),s,ea=c(e,"MiddleRight")),c(e,!1,"clear:left").append(c(e,"BottomLeft"),fa=c(e,"BottomCenter"),c(e,"BottomRight"))).find("div div").css({"float":"left"}),L=c(e,!1,"position:absolute; width:9999px; visibility:hidden; display:none"),X=J.add(K).add(ba).add(E),b(D.body).append(y,i.append(C,L)))}var U={transition:"elastic",speed:300,width:!1,initialWidth:"600",innerWidth:!1,maxWidth:!1,height:!1,initialHeight:"450",innerHeight:!1,maxHeight:!1,
scalePhotos:!0,scrolling:!0,inline:!1,html:!1,iframe:!1,fastIframe:!0,photo:!1,href:!1,title:!1,rel:!1,opacity:0.9,preloading:!0,current:"image {current} of {total}",previous:"previous",next:"next",close:"close",xhrError:"This content failed to load.",imgError:"This image failed to load.",open:!1,returnFocus:!0,reposition:!0,loop:!0,slideshow:!1,slideshowAuto:!0,slideshowSpeed:2500,slideshowStart:"start slideshow",slideshowStop:"stop slideshow",onOpen:!1,onLoad:!1,onComplete:!1,onCleanup:!1,onClosed:!1,
overlayClose:!0,escKey:!0,arrowKey:!0,top:!1,bottom:!1,left:!1,right:!1,fixed:!1,data:void 0},t="colorbox",p="cbox",F=p+"Element",ka=p+"_open",W=p+"_load",V=p+"_complete",Q=p+"_cleanup",ja=p+"_closed",T=p+"_purge",I=!b.support.opacity&&!b.support.style,H=I&&!M.XMLHttpRequest,S=p+"_IE6",y,i,C,s,ca,da,ea,fa,j,q,l,L,aa,Y,ba,E,J,K,Z,X,a,z,A,v,w,m,n,d,u,G,R,ma,f,e="div",$;b.colorbox||(b(la),f=b.fn[t]=b[t]=function(c,e){var d=this,c=c||{};la();var k;i?($||($=!0,z=ca.height()+fa.height()+s.outerHeight(!0)-
s.height(),A=da.width()+ea.width()+s.outerWidth(!0)-s.width(),v=l.outerHeight(!0),w=l.outerWidth(!0),i.css({"padding-bottom":z,"padding-right":A}),J.click(function(){f.next()}),K.click(function(){f.prev()}),Z.click(function(){f.close()}),y.click(function(){a.overlayClose&&f.close()}),b(D).bind("keydown."+p,function(b){var c=b.keyCode;u&&(a.escKey&&27===c)&&(b.preventDefault(),f.close());u&&(a.arrowKey&&j[1])&&(37===c?(b.preventDefault(),K.click()):39===c&&(b.preventDefault(),J.click()))}),b("."+F,
D).live("click",function(a){1<a.which||(a.shiftKey||a.altKey||a.metaKey)||(a.preventDefault(),ia(this))})),k=!0):k=!1;if(k){if(!d[0]){if(d.selector)return d;d=b("<a/>");c.open=!0}e&&(c.onComplete=e);d.each(function(){b.data(this,t,b.extend({},b.data(this,t)||U,c))}).addClass(F);(b.isFunction(c.open)&&c.open.call(d)||c.open)&&ia(d[0])}return d},f.position=function(b,c){function e(a){ca[0].style.width=fa[0].style.width=s[0].style.width=a.style.width;s[0].style.height=da[0].style.height=ea[0].style.height=
a.style.height}var d,r=d=0,j=i.offset(),l,n;q.unbind("resize."+p);i.css({top:-9E4,left:-9E4});l=q.scrollTop();n=q.scrollLeft();a.fixed&&!H?(j.top-=l,j.left-=n,i.css({position:"fixed"})):(d=l,r=n,i.css({position:"absolute"}));r=!1!==a.right?r+Math.max(O()-a.w-w-A-h(a.right,"x"),0):!1!==a.left?r+h(a.left,"x"):r+Math.round(Math.max(O()-a.w-w-A,0)/2);d=!1!==a.bottom?d+Math.max(P()-a.h-v-z-h(a.bottom,"y"),0):!1!==a.top?d+h(a.top,"y"):d+Math.round(Math.max(P()-a.h-v-z,0)/2);i.css({top:j.top,left:j.left});
b=i.width()===a.w+w&&i.height()===a.h+v?0:b||0;C[0].style.width=C[0].style.height="9999px";d={width:a.w+w,height:a.h+v,top:d,left:r};0===b&&i.css(d);i.dequeue().animate(d,{duration:b,complete:function(){e(this);G=!1;C[0].style.width=a.w+w+A+"px";C[0].style.height=a.h+v+z+"px";a.reposition&&setTimeout(function(){q.bind("resize."+p,f.position)},1);c&&c()},step:function(){e(this)}})},f.resize=function(b){u&&(b=b||{},b.width&&(a.w=h(b.width,"x")-w-A),b.innerWidth&&(a.w=h(b.innerWidth,"x")),l.css({width:a.w}),
b.height&&(a.h=h(b.height,"y")-v-z),b.innerHeight&&(a.h=h(b.innerHeight,"y")),!b.innerHeight&&!b.height&&(l.css({height:"auto"}),a.h=l.height()),l.css({height:a.h}),f.position("none"===a.transition?0:a.speed))},f.prep=function(h){function g(){a.w=a.w||l.width();a.w=a.mw&&a.mw<a.w?a.mw:a.w;return a.w}function m(){a.h=a.h||l.height();a.h=a.mh&&a.mh<a.h?a.mh:a.h;return a.h}if(u){var k,r="none"===a.transition?0:a.speed;l.remove();l=c(e,"LoadedContent").append(h);l.hide().appendTo(L.show()).css({width:g(),
overflow:a.scrolling?"auto":"hidden"}).css({height:m()}).prependTo(s);L.hide();b(d).css({"float":"none"});if(H)b("select").not(i.find("select")).filter(function(){return"hidden"!==this.style.visibility}).css({visibility:"hidden"}).one(Q,function(){this.style.visibility="inherit"});k=function(){function e(){I&&i[0].style.removeAttribute("filter")}var f,g;f=j.length;var h,m,k;if(u){m=function(){clearTimeout(ma);aa.detach().hide();B(V,a.onComplete)};I&&d&&l.fadeIn(100);Y.html(a.title).add(l).show();
if(1<f){if("string"===typeof a.current&&ba.html(a.current.replace("{current}",n+1).replace("{total}",f)).show(),J[a.loop||n<f-1?"show":"hide"]().html(a.next),K[a.loop||n?"show":"hide"]().html(a.previous),a.slideshow&&E.show(),a.preloading)for(f=[N(-1),N(1)];g=j[f.pop()];)(k=b.data(g,t))&&k.href?(k=k.href,b.isFunction(k)&&(k=k.call(g))):k=g.href,ga(k)&&(g=new Image,g.src=k)}else X.hide();a.iframe?(h=c("iframe")[0],"frameBorder"in h&&(h.frameBorder=0),"allowTransparency"in h&&(h.allowTransparency="true"),
a.scrolling||(h.scrolling="no"),b(h).attr({src:a.href,name:(new Date).getTime(),"class":p+"Iframe",allowFullScreen:!0,webkitAllowFullScreen:!0,mozallowfullscreen:!0}).one("load",m).one(T,function(){h.src="//about:blank"}).appendTo(l),a.fastIframe&&b(h).trigger("load")):m();"fade"===a.transition?i.fadeTo(r,1,e):e()}};"fade"===a.transition?i.fadeTo(r,0,function(){f.position(0,k)}):f.position(r,k)}},f.load=function(i){var g,q,k=f.prep;G=!0;d=!1;m=j[n];i||ha();B(T);B(W,a.onLoad);a.h=a.height?h(a.height,
"y")-v-z:a.innerHeight&&h(a.innerHeight,"y");a.w=a.width?h(a.width,"x")-w-A:a.innerWidth&&h(a.innerWidth,"x");a.mw=a.w;a.mh=a.h;a.maxWidth&&(a.mw=h(a.maxWidth,"x")-w-A,a.mw=a.w&&a.w<a.mw?a.w:a.mw);a.maxHeight&&(a.mh=h(a.maxHeight,"y")-v-z,a.mh=a.h&&a.h<a.mh?a.h:a.mh);g=a.href;ma=setTimeout(function(){aa.show().appendTo(s)},100);a.inline?(c(e).hide().insertBefore(b(g)[0]).one(T,function(){b(this).replaceWith(l.children())}),k(b(g))):a.iframe?k(" "):a.html?k(a.html):ga(g)?(b(d=new Image).addClass(p+
"Photo").error(function(){a.title=!1;k(c(e,"Error").html(a.imgError))}).load(function(){var b;d.onload=null;a.scalePhotos&&(q=function(){d.height-=d.height*b;d.width-=d.width*b},a.mw&&d.width>a.mw&&(b=(d.width-a.mw)/d.width,q()),a.mh&&d.height>a.mh&&(b=(d.height-a.mh)/d.height,q()));a.h&&(d.style.marginTop=Math.max(a.h-d.height,0)/2+"px");if(j[1]&&(a.loop||j[n+1]))d.style.cursor="pointer",d.onclick=function(){f.next()};I&&(d.style.msInterpolationMode="bicubic");setTimeout(function(){k(d)},1)}),setTimeout(function(){d.src=
g},1)):g&&L.load(g,a.data,function(d,f){k("error"===f?c(e,"Error").html(a.xhrError):b(this).contents())})},f.next=function(){if(!G&&j[1]&&(a.loop||j[n+1]))n=N(1),f.load()},f.prev=function(){if(!G&&j[1]&&(a.loop||n))n=N(-1),f.load()},f.close=function(){u&&!R&&(R=!0,u=!1,B(Q,a.onCleanup),q.unbind("."+p+" ."+S),y.fadeTo(200,0),i.stop().fadeTo(300,0,function(){i.add(y).css({opacity:1,cursor:"auto"}).hide();B(T);l.remove();setTimeout(function(){R=!1;B(ja,a.onClosed)},1)}))},f.remove=function(){b([]).add(i).add(y).remove();
i=null;b("."+F).removeData(t).removeClass(F).die()},f.element=function(){return b(m)},f.settings=U)})(jQuery,document,window);

//Zoom Image Generator
function generateZoomImage(a){a.css({overflow:"hidden"});a.append("<div id='zoomArea'>"+a.html()+"</div>");var c=$("div#zoomArea");c.css({position:"absolute",display:"none"});a.mousemove(function(b){var d=b.pageX-a.offset().left,b=b.pageY-a.offset().top,d=d/a.width(),b=b/a.height(),d=-1*d*(c.width()-a.width()),b=-1*b*(c.height()-a.height());c.css({top:b,left:d})});a.hover(function(){c.fadeIn()},function(){c.fadeOut()})};

//Images Loaded?? plugin
(function(c,n){var l="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";c.fn.imagesLoaded=function(f){function m(){var b=c(i),a=c(h);d&&(h.length?d.reject(e,b,a):d.resolve(e));c.isFunction(f)&&f.call(g,e,b,a)}function j(b,a){b.src===l||-1!==c.inArray(b,k)||(k.push(b),a?h.push(b):i.push(b),c.data(b,"imagesLoaded",{isBroken:a,src:b.src}),o&&d.notifyWith(c(b),[a,e,c(i),c(h)]),e.length===k.length&&(setTimeout(m),e.unbind(".imagesLoaded")))}var g=this,d=c.isFunction(c.Deferred)?c.Deferred():
0,o=c.isFunction(d.notify),e=g.find("img").add(g.filter("img")),k=[],i=[],h=[];c.isPlainObject(f)&&c.each(f,function(b,a){if("callback"===b)f=a;else if(d)d[b](a)});e.length?e.bind("load.imagesLoaded error.imagesLoaded",function(b){j(b.target,"error"===b.type)}).each(function(b,a){var d=a.src,e=c.data(a,"imagesLoaded");if(e&&e.src===d)j(a,e.isBroken);else if(a.complete&&a.naturalWidth!==n)j(a,0===a.naturalWidth||0===a.naturalHeight);else if(a.readyState||a.complete)a.src=l,a.src=d}):m();return d?d.promise(g):
g}})(jQuery);